name: android-studio-canary
version: 2025.1.1.9
summary: The IDE for Android (Canary build)
description: |
  Android Studio provides the fastest tools for building apps on every type
  of Android device.

  World-class code editing, debugging, performance tooling, a flexible build
  system, and an instant build/deploy system all allow you to focus on
  building unique and high quality apps.
base: core22

grade: stable
confinement: classic
compression: lzo
architectures:
  - build-on: amd64

apps:
  android-studio-canary:
    command: bin/studio.sh
    environment:
      PULSE_SERVER: $XDG_RUNTIME_DIR/pulse/native

parts:
  android-studio-canary:
    plugin: dump
    source: https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2025.1.1.9/android-studio-2025.1.1.9-linux.tar.gz
    build-attributes:
      - no-patchelf